apiVersion: v1
kind: Secret
metadata:
  name: exchange-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.accountSecrets.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.accountSecrets.password | quote }}
  SPRING_DATASOURCE_DB: {{ .Values.accountSecrets.db | quote }}