openapi: 3.0.3
info:
  title: Account API
  version: 1.0.0
  description: API для управления банковскими счетами пользователей

servers:
  - url: http://localhost:8080/api/account

security:
  - bearerAuth: [ ]

paths:
  /user:
    get:
      summary: Получить список счетов пользователя
      operationId: getAccounts
      tags:
        - Account
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: Список счетов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountDto'
    post:
      summary: Создать новый счёт
      operationId: addAccount
      tags:
        - Account
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountDto'
      responses:
        '201':
          description: Счёт успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDto'

  /user/{id}:
    get:
      summary: Получить счёт по ID
      operationId: getAccount
      tags:
        - Account
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
          description: ID счёта
      responses:
        '200':
          description: Данные счёта
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDto'
    delete:
      summary: Удалить счёт по ID
      operationId: deleteAccount
      tags:
        - Account
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
          description: ID счёта
      responses:
        '200':
          description: Счёт удалён

components:
  schemas:
    AccountDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1001
        number:
          type: string
          example: "40817810099910004321"
        userId:
          type: string
          example: "user-123"
        balance:
          type: number
          format: double
          example: 15000.75
        status:
          $ref: '#/components/schemas/AccountStatus'
        currency:
          $ref: '#/components/schemas/Currency'

    AccountStatus:
      type: string
      enum:
        - ACTIVE
        - BLOCKED
        - CLOSED

    Currency:
      type: string
      enum:
        - RUB
        - USD
        - EUR
