image:
  repository: cash-practicum-bank
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8083

env:
  JAVA_OPTS: "-Xms256m -Xmx512m"

configMap:
  jwtIssuerUri: "http://keycloak:8080/realms/bank"
  api:
    account: "http://localhost:8080/api/account"
    cash: "http://localhost:8080/api/cash"
    blocker: "http://localhost:8080/api/blocker"
    notification: "http://localhost:8080/api/notification"

resources: {}