
spring:
  application:
    name: gateway

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true

server:
  port: 8080
  forward-headers-strategy: framework