apiVersion: v1
kind: ConfigMap
metadata:
  name: exchange-generator-config
data:
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URL: "http://keycloak:8080/realms/bank/protocol/openid-connect/token"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URL: "http://keycloak:8080/realms/bank"
  API_EXCHANGE: "http://localhost:8080/api/exchange"
