
spring:
  application:
    name: practicum-bank-frontend-ui
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${FRONTEND_UI_OAUTH2_CLIENT_ID}
            client-secret: ${FRONTEND_UI_OAUTH2_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: "${KEYCLOAK_URL}/realms/${OAUTH2_REALM}"


keycloak-admin:
  server-url: ${KEYCLOAK_URL}
  username: ${KEYCLOAK_ADMIN}
  password:  ${KEYCLOAK_ADMIN_PASSWORD}
  realm:  ${OAUTH2_REALM}