apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: practicum-bank-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /api/account
            pathType: Prefix
            backend:
              service:
                name: account
                port:
                  number: {{ .Values.account.service.port }}

          - path: /api/blocker
            pathType: Prefix
            backend:
              service:
                name: blocker
                port:
                  number: {{ .Values.blocker.service.port }}

          - path: /api/cash
            pathType: Prefix
            backend:
              service:
                name: cash
                port:
                  number: {{ .Values.cash.service.port }}

          - path: /api/exchange
            pathType: Prefix
            backend:
              service:
                name: exchange
                port:
                  number: {{ .Values.exchange.service.port }}

          - path: /api/exchange-generator
            pathType: Prefix
            backend:
              service:
                name: exchange-generator
                port:
                  number: {{ index .Values "exchange-generator" "service" "port" }}

          - path: /api/notification
            pathType: Prefix
            backend:
              service:
                name: notification
                port:
                  number: {{ .Values.notification.service.port }}

          - path: /api/transfer
            pathType: Prefix
            backend:
              service:
                name: transfer
                port:
                  number: {{ .Values.transfer.service.port }}


          - path: /realms
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: {{ .Values.keycloak.service.port }}

          - path: /login/oauth2/code
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: {{ .Values.keycloak.service.port }}

          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: {{ .Values.keycloak.service.port }}


          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-ui
                port:
                  number: {{ index .Values "front-ui" "service" "port" }}

          - path: /account
            pathType: Prefix
            backend:
              service:
                name: front-ui
                port:
                  number: {{ index .Values "front-ui" "service" "port" }}

          - path: /cash
            pathType: Prefix
            backend:
              service:
                name: front-ui
                port:
                  number: {{ index .Values "front-ui" "service" "port" }}

          - path: /transfer
            pathType: Prefix
            backend:
              service:
                name: front-ui
                port:
                  number: {{ index .Values "front-ui" "service" "port" }}

          - path: /user
            pathType: Prefix
            backend:
              service:
                name: front-ui
                port:
                  number: {{ index .Values "front-ui" "service" "port" }}
