apiVersion: v1
kind: ConfigMap
metadata:
  name: transfer-config
data:
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: {{ .Values.configMap.jwtIssuerUri | quote}}
  API_ACCOUNT: {{ .Values.configMap.api.account | quote}}
  API_CASH: {{ .Values.configMap.api.cash | quote}}
  API_BLOCKER: {{ .Values.configMap.api.blocker | quote}}
  API_NOTIFICATION: {{ .Values.configMap.api.notification | quote}}
  API_EXCHANGE: {{ .Values.configMap.api.exchange | quote}}
  SERVER_PORT: {{ .Values.service.port | quote }}