apiVersion: v1
kind: ConfigMap
metadata:
  name: front-ui-config
data:
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: "http://keycloak:8080/realms/bank"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_REDIRECT_URL: "http://localhost:8080/login/oauth2/code/{registrationId}"
  API_ACCOUNT: "http://localhost:8080/api/account"
  API_CASH: "http://localhost:8080/api/cash"
  API_TRANSFER: "http://localhost:8080/api/transfer"
