apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgresSecret.db | quote }}
  POSTGRES_USER: {{ .Values.postgresSecret.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresSecret.password | quote }}
