apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
type: Opaque
stringData:
  SPRING_MAIL_HOST: {{ .Values.notificationSecrets.mail.host | quote }}
  SPRING_MAIL_PORT: {{ .Values.notificationSecrets.mail.port | quote }}
  SPRING_MAIL_USERNAME: {{ .Values.notificationSecrets.mail.username | quote }}
  SPRING_MAIL_PASSWORD: {{ .Values.notificationSecrets.mail.password | quote }}