apiVersion: v1
kind: Secret
metadata:
  name: account-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.accountSecrets.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.accountSecrets.password | quote }}
  SPRING_DATASOURCE_DB: {{ .Values.accountSecrets.db | quote }}
  ACCOUNT_SERVICE_OAUTH2_CLIENT_ID: {{ .Values.accountSecrets.oauth2_client_id | quote }}
  ACCOUNT_SERVICE_OAUTH2_CLIENT_SECRET: {{ .Values.accountSecrets.oauth2_client_secret | quote }}