account:
  configMap:
    datasourceUrl: "jdbc:postgresql://postgres:5432/accounts"
    jwtIssuerUri: "http://keycloak:8080/realms/bank"

blocker:
  configMap:
    jwtIssuerUri: "http://keycloak:8080/realms/bank"

cash:
  configMap:
    jwtIssuerUri: "http://keycloak:8080/realms/bank"
    api:
      account: "http://account:8082"
      cash: "http://cash:8083"
      blocker: "http://blocker:8087"
      notification: "http://notification:8088"

exchange:
  configMap:
    datasourceUrl: "jdbc:postgresql://postgres:5432/exchange"
    jwtIssuerUri: "http://keycloak:8080/realms/bank"

exchange-generator:
  configMap:
    jwtIssuerUri: "http://keycloak:8080/realms/bank"
    keycloakTokenUrl: "http://keycloak:8080/realms/bank/protocol/openid-connect/token"
    api:
      exchange: "http://exchange"


front-ui:
  configMap:
    jwtIssuerUri: "http://keycloak:8080/realms/bank"
    keycloakTokenUrl: "http://keycloak:8080/realms/bank/protocol/openid-connect/token"
    keycloakRedirectUrl: "http://localhost/login/oauth2/code/{registrationId}"
    api:
      account: "http://account:8082"
      cash: "http://cash:8083"
      blocker: "http://blocker:8087"
      notification: "http://notification:8088"
      exchange: "http://exchange:8084"
      transfer: "http://transfer:8086"

keycloak:
  postgres:
    host: "postgres"
    port: 5432
    db: "keycloak"

notification:
  configMap:
    jwtIssuerUri: "http://keycloak:8080/realms/bank"

transfer:
  configMap:
    jwtIssuerUri: "http://keycloak:8080/realms/bank"
    api:
      account: "http://account:8082"
      cash: "http://cash:8083"
      blocker: "http://blocker:8087"
      notification: "http://notification:8088"
      exchange: "http://exchange:8084"
      transfer: "http://transfer:8086"